sudo: false   # Use container-based infrastructure.
language: python

matrix:
    include:
    - python: 3.5
      env:
        - PYTHON_VERSION="3.5"
        - PYTEST_ARGS="-v"
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"
        - PYTEST_ARGS="-v"

# Create a test environment and install dependencies.
install: source continuous_integration/install.sh
# Command to run tests.
script: eval pytest
